# Generated by Django 5.1.7 on 2026-02-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('position', models.CharField(choices=[('header', 'Main Header'), ('footer_company', 'Footer Company'), ('footer_links', 'Footer Quick Links'), ('dashboard_sidebar', 'Dashboard Sidebar')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
