# Generated by Django 5.1.7 on 2026-02-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_navigationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prompt_text', models.TextField()),
                ('category', models.CharField(choices=[('story_write', 'Story Writing'), ('seo_gen', 'SEO Generation'), ('desc_gen', 'Description Generation'), ('general', 'General')], default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Prompt',
                'verbose_name_plural': 'AI Prompts',
            },
        ),
        migrations.CreateModel(
            name='LayoutSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(help_text='Can be a string, hex color, or JSON')),
                ('setting_type', models.CharField(choices=[('color', 'Color'), ('text', 'Text'), ('boolean', 'Switch'), ('json', 'Complex JSON')], default='text', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
