# Generated by Django 6.0.2 on 2026-02-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_story_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(blank=True, default='Editorial Team', max_length=200),
        ),
    ]
