# Generated by Django 6.0.2 on 2026-02-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_story_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='sections',
            field=models.JSONField(blank=True, help_text='Structured sections like The Problem, The Solution, etc.', null=True),
        ),
    ]
