# Generated by Django 5.1.7 on 2026-02-09 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_story_stage_views_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, help_text='HTML or plain text')),
                ('column_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['column_order'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='media/')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='pages/og/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='city',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og_images/'),
        ),
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='content',
            field=models.TextField(blank=True, help_text='For custom_content type'),
        ),
        migrations.AddField(
            model_name='startupsubmission',
            name='full_story',
            field=models.TextField(blank=True, help_text='Full startup story'),
        ),
        migrations.AddField(
            model_name='startupsubmission',
            name='funding_stage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='startupsubmission',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='aiprompt',
            name='category',
            field=models.CharField(choices=[('seo_rewrite', 'SEO Rewrite'), ('title_generation', 'Title Generation'), ('meta_description', 'Meta Description'), ('social_captions', 'Social Captions'), ('story_write', 'Story Writing'), ('desc_gen', 'Description Generation'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='page',
            field=models.CharField(choices=[('homepage', 'Homepage'), ('stories', 'Stories Listing'), ('startups', 'Startups Listing'), ('city', 'City Detail'), ('category', 'Category Detail'), ('footer', 'Footer'), ('custom', 'Custom Page')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('banner', 'Hero Banner'), ('featured_stories', 'Featured Stories'), ('latest_stories', 'Latest Stories'), ('category_grid', 'Category Grid'), ('city_grid', 'City Grid'), ('startup_cards', 'Startup Cards'), ('featured_startups', 'Featured Startups'), ('cta', 'Call to Action'), ('newsletter', 'Newsletter Section'), ('custom_content', 'Custom Content Block'), ('icons', 'Icons Grid'), ('testimonials', 'Testimonials'), ('footer_content', 'Footer Content'), ('text_block', 'Text Block')], max_length=50),
        ),
        migrations.AlterField(
            model_name='startupsubmission',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='startupsubmission',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='startupsubmission',
            name='description',
            field=models.TextField(blank=True, help_text='Short description'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='page_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.page'),
        ),
    ]
