# Generated by Django 5.1.7 on 2026-02-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_footersetting_mediaitem_page_seosetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageThemeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('homepage', 'Homepage'), ('stories_list', 'Stories Listing'), ('stories_detail', 'Story Detail'), ('startups_list', 'Startups Listing'), ('startups_detail', 'Startup Detail'), ('categories_list', 'Categories Listing'), ('categories_detail', 'Category Detail'), ('cities_list', 'Cities Listing'), ('cities_detail', 'City Detail'), ('submit', 'Submit Page')], max_length=50, unique=True)),
                ('theme_overrides', models.JSONField(blank=True, help_text='bg_color, font_family, accent_color, dropdown_style, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='theme_overrides',
            field=models.JSONField(blank=True, help_text='Per-page styling: bg_color, font_family, accent_color, etc.', null=True),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='settings',
            field=models.JSONField(blank=True, help_text='Section styling: bg_color, font_size, border_radius, dropdown_style, etc.', null=True),
        ),
    ]
