# Generated by Django 6.0.2 on 2026-02-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_theme_page_section_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='startup_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='tier',
            field=models.CharField(choices=[('1', 'Tier 1'), ('2', 'Tier 2'), ('3', 'Tier 3')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='city',
            name='unicorn_count',
            field=models.IntegerField(default=0),
        ),
    ]
