# Generated by Django 6.0.2 on 2026-02-10 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_city_startup_count_city_tier_city_unicorn_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.navigationitem'),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='settings',
            field=models.JSONField(blank=True, help_text='Custom styling: color, weight, is_mega_menu, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
