# Generated by Django 5.1.7 on 2026-02-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_navigationitem_parent_navigationitem_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(blank=True, default='', help_text='Lucide icon name e.g. credit-card, cloud, shopping-cart', max_length=50),
        ),
    ]
