# Generated by Django 5.1.7 on 2026-02-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alter_pagesection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='founders_data',
            field=models.JSONField(blank=True, help_text='List of founders: [{"name": "...", "role": "...", "linkedin": "...", "image": "..."}]', null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='sector',
            field=models.CharField(blank=True, help_text='e.g. B2C, B2B', max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='stage',
            field=models.CharField(blank=True, help_text='e.g. Series F, Seed, Unicorn', max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='tagline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='startup',
            name='team_size',
            field=models.CharField(blank=True, help_text='e.g. 3000+ employees', max_length=100),
        ),
    ]
