# Generated by Django 6.0.2 on 2026-02-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_startup_founders_data_startup_sector_startup_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompt',
            name='category',
            field=models.CharField(choices=[('story_write', 'Story Writing'), ('seo_gen', 'SEO Generation'), ('desc_gen', 'Description Generation'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
