# Generated by Django 6.0.2 on 2026-02-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_alter_aiprompt_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
