# Generated by Django 5.1.7 on 2026-02-17 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_path', models.CharField(help_text='e.g. /stories/old-slug', max_length=500, unique=True)),
                ('to_path', models.CharField(help_text='e.g. /stories/new-slug', max_length=500)),
                ('is_permanent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['from_path'],
            },
        ),
        migrations.RemoveField(
            model_name='startup',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='stage',
        ),
        migrations.AddField(
            model_name='page',
            name='canonical_override',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='business_model',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('both', 'Both')], max_length=10),
        ),
        migrations.AddField(
            model_name='startup',
            name='canonical_override',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='funding_stage',
            field=models.CharField(blank=True, help_text='e.g. Seed, Series A, Unicorn', max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='industry_tags',
            field=models.JSONField(blank=True, help_text='List of industry tag strings', null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='canonical_override',
            field=models.URLField(blank=True, help_text='Override canonical URL'),
        ),
        migrations.AddField(
            model_name='story',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='read_time',
            field=models.PositiveIntegerField(blank=True, help_text='Read time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published'), ('blocked', 'Blocked')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='startup',
            name='team_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='sections',
            field=models.JSONField(blank=True, help_text='Structured sections: The Problem, The Solution, Founder Journey, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='founders/photos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='cms.startup')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
