# Generated by Django 5.1.7 on 2026-02-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_spec_models_redirect_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='position',
            field=models.CharField(choices=[('header', 'Main Header'), ('footer', 'Main Footer'), ('footer_company', 'Footer Company'), ('footer_links', 'Footer Quick Links'), ('sidebar', 'Main Sidebar'), ('dashboard_sidebar', 'Dashboard Sidebar')], max_length=50),
        ),
    ]
