# Generated by Django 5.1.7 on 2026-02-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_alter_navigationitem_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('banner', 'Hero Banner'), ('featured_stories', 'Featured Stories'), ('latest_stories', 'Latest Stories'), ('category_grid', 'Category Grid'), ('city_grid', 'City Grid (Top Cities)'), ('rising_hubs', 'Rising Startup Hubs (Tier 2/3)'), ('startup_cards', 'Startup Cards'), ('featured_startups', 'Featured Startups'), ('cta', 'Call to Action'), ('newsletter', 'Newsletter Section'), ('custom_content', 'Custom Content Block'), ('icons', 'Icons Grid'), ('testimonials', 'Testimonials'), ('footer_content', 'Footer Content'), ('text_block', 'Text Block'), ('text', 'Text Content'), ('image', 'Image Block'), ('video', 'Video Block')], max_length=50),
        ),
    ]
