# Generated by Django 6.0.2 on 2026-02-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_alter_pagesection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated SEO keywords'),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated SEO keywords'),
        ),
        migrations.AddField(
            model_name='startup',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated SEO keywords'),
        ),
        migrations.AddField(
            model_name='story',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for featured image', max_length=300),
        ),
        migrations.AddField(
            model_name='story',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated SEO keywords'),
        ),
        migrations.AddField(
            model_name='story',
            name='show_table_of_contents',
            field=models.BooleanField(default=True),
        ),
    ]
