# Generated by Django 6.0.2 on 2026-02-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_category_meta_keywords_city_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='business_model',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('b2b2c', 'B2B2C'), ('d2c', 'D2C'), ('saas', 'SaaS'), ('marketplace', 'Marketplace'), ('subscription', 'Subscription'), ('freemium', 'Freemium'), ('platform', 'Platform'), ('other', 'Other')], max_length=30),
        ),
    ]
