# Generated by Django 6.0.2 on 2026-02-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_alter_startup_business_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupsubmission',
            name='business_model',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
