# Generated by Django 6.0.2 on 2026-02-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_alter_pagesection_section_type'),
        ('cms', '0022_startupsubmission_business_model'),
    ]

    operations = [
    ]
