# Generated by Django 6.0.2 on 2026-02-20 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_merge_20260220_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
