# Generated by Django 6.0.2 on 2026-02-20 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_newslettersubscription_last_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Weekly Newsletter', max_length=100)),
                ('subject_format', models.CharField(default='StartupSaga Weekly: {first_story_title}', max_length=255)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('font_family', models.CharField(default="-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif", max_length=255)),
                ('header_title', models.CharField(default='StartupSaga', max_length=255)),
                ('header_subtitle', models.CharField(default='Weekly stories, founder insights, and ecosystem updates', max_length=255)),
                ('body_intro', models.CharField(default='Top Stories This Week', max_length=255)),
                ('footer_text', models.TextField(default='© {year} StartupSaga. All rights reserved.\nYou received this email because you subscribed to our newsletter.')),
                ('accent_color', models.CharField(default='#ea580c', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
