# Generated by Django 5.2.11 on 2026-03-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_newslettertemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for logo/featured image', max_length=300),
        ),
    ]
