# Generated by Django 5.1.7 on 2026-02-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_newslettertemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='tagline',
            field=models.TextField(blank=True),
        ),
    ]
