# Generated by Django 5.1.7 on 2026-02-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_alter_startup_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for logo/featured image', max_length=300),
        ),
    ]
