# Generated by Django 5.1.7 on 2026-03-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_startup_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupsubmission',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for logo/thumbnail', max_length=300),
        ),
        migrations.AddField(
            model_name='startupsubmission',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='startupsubmission',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated SEO keywords'),
        ),
        migrations.AddField(
            model_name='startupsubmission',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='startupsubmission',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og_images/'),
        ),
    ]
