# Generated by Django 5.2.11 on 2026-03-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_startupsubmission_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
