# Generated by Django 5.2.11 on 2026-03-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_alter_startup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
