# Generated by Django 5.2.11 on 2026-03-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_alter_story_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
