# Generated by Django 5.2.11 on 2026-03-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_newslettersubscription_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettertemplate',
            name='body_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
