# Generated by Django 5.2.11 on 2026-03-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_newslettertemplate_body_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettertemplate',
            name='admin_body_intro',
            field=models.CharField(default='Fresh Lead', max_length=255),
        ),
        migrations.AddField(
            model_name='newslettertemplate',
            name='admin_body_text',
            field=models.TextField(blank=True, default='<p>A user has just subscribed to the newsletter:</p>'),
        ),
    ]
